// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package client

import "fyne.io/fyne/v2"

var VersionText = &fyne.StaticResource{
	StaticName: "version.txt",
	StaticContent: []byte(
		"0.0.1\n"),
}
